### PR TITLE
Add more packages using conda-forge

### PR DESCRIPTION
**Pull request by robertodr**

### CODE REVIEW

**Comment by haraldschilly** [comment]
ok, this is built and deployed. you might have to restart your project to get the update...

importing `tqdm.notebook` works fine, see below

Screenshot from 2020-06-04 12-00-43

**Comment by robertodr** [comment]
Thanks for the heads-up. Is there a way to monitor progress of building images?

**Comment by haraldschilly** [comment]
No, it's me doing it in a terminal and checking if it worked. Then it's deployed to the cluster that runs cocalc.

**Comment by robertodr** [comment]
OK, I see.

**Pull request merged**
